INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl) VALUES ('Completeness', 'Completeness');
INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl, FunctionType) VALUES ('DeleteDataObject', 'DeleteDataObject', 'P');
INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl) VALUES ('Uniqueness', 'Uniqueness');
INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl) VALUES ('Entirety', 'Entirety');
INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl) VALUES ('Consistency', 'Consistency');
INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl, FunctionType) VALUES ('ValidityRange', 'ValidityRange', 'V');
INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl, FunctionType) VALUES ('CurveSpikes', 'CurveSpikes', 'V');
INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl, FunctionType) VALUES ('IsNumber', 'IsNumber', 'V');
INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl, FunctionType) VALUES ('PredictDepthUsingIDW', 'PredictDepthUsingIDW', 'P');
INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl, FunctionType) VALUES ('PredictDominantLithology', 'PredictDominantLithology', 'P');
INSERT INTO pdo_rule_functions (FunctionName, FunctionUrl, FunctionType) VALUES ('PredictFormationOrder', 'PredictFormationOrder', 'P');