name: DeployServerlessUI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build release
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish DatabaseManager.ServerLessClient/DatabaseManager.ServerLessClient.csproj --configuration Release -o ../published_app --no-build --self-contained true
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ServerlessUI
          path: D:\a\DatabaseManager\published_app\wwwroot
          
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ServerlessUI
    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    - name: Deploy to storage using CLI
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: | 
          # show azure account being used
          az account show
          # az storage account upload
          az storage blob upload-batch --account-name ${{ secrets.SERVERLESSUI_BLOB_STORAGE_ACCOUNT_NAME }} -s . -d \$web
    - name: logout
      working-directory: .
      run: |
        az logout
  
