name: DatabaseManagerBuild

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'   
        required: true
  
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build DatabaseManager.ServerLessClient/DatabaseManager.ServerLessClient.csproj --no-restore
      - name: Publish
        run: dotnet publish DatabaseManager.ServerLessClient/DatabaseManager.ServerLessClient.csproj
      - name: Upload ServerlessUI Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ServerlessUI
          path: D:\a\DatabaseManager\DatabaseManager\DatabaseManager.ServerLessClient\bin\Debug\net6.0\publish\
