name: DatabaseManagerBuild

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'   
        required: true
  
jobs:
  release:
    name: Release ConsoleTestStuff 
    runs-on: windows-2022
    needs: build
    steps:
    - name: Download serverlessUI content
      uses: actions/download-artifact@v2
      with:
        name: ServerlessUI
    - name: Archive content
      uses: thedoctor0/zip-release@master
      with:
        filename: serverlessUI.zip
    - name: Create github release
      id: create-new-release 
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.versionNumber }}
        release_name: Release V${{ github.event.inputs.versionNumber }}
        body_path: CHANGELOG.md
    - name: Upload asset to Github release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./serverlessUI.zip
        asset_name: serverlessUI-v${{ github.event.inputs.versionNumber }}.zip
        asset_content_type: application/zip
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build DatabaseManager.ServerLessClient/DatabaseManager.ServerLessClient.csproj --no-restore
      - name: Publish
        run: dotnet publish DatabaseManager.ServerLessClient/DatabaseManager.ServerLessClient.csproj
      - name: Upload ServerlessUI Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ServerlessUI
          path: D:\a\DatabaseManager\DatabaseManager\DatabaseManager.ServerLessClient\bin\Debug\net6.0\publish\
