name: DatabaseManagerRelease

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'   
        required: true
  
jobs:
  changelog:
    name: Prepare changelog
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Upload Changelog Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ChangelogStuff
          path: ./CHANGELOG.md
          
  build:
    name: Build release
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Install dependencies
        run: dotnet restore DatabaseManager/server/DatabaseManager.Server.csproj
        
      - name: Build
        run: dotnet build DatabaseManager/server/DatabaseManager.Server.csproj --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish DatabaseManager/server/DatabaseManager.Server.csproj
        
      - name: Upload Hosted Server Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: HostedServer
          path: D:\a\DatabaseManager\DatabaseManager\DatabaseManager\Server\bin\Debug\net6.0\publish\
          
  release:
    name: Release Project
    runs-on: windows-2022
    needs: build
    steps:
      - name: Download changelog
        uses: actions/download-artifact@v2
        with:
            name: ChangelogStuff
            
      - name: Create release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.versionNumber }}
          release_name: Release V${{ github.event.inputs.versionNumber }}
          body_path: "./CHANGELOG.md"
          
      - name: Download site content HostedServer
        uses: actions/download-artifact@v2
        with:
          name: HostedServer
          path: hostedserver
      - name: View HostedServer content
        run: dir hostedserver
      - name: Archive HostedServer content
        uses: thedoctor0/zip-release@master
        with:
          directory: hostedserver
          filename: HostedServer.zip
      - name: Upload HostedServer release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./hostedserver/HostedServer.zip
          asset_name: HostedServer-v${{ github.event.inputs.versionNumber }}.zip
          asset_content_type: application/zip
