name: DatabaseManagerRelease

on:
  workflow_dispatch:
  
jobs:
  changelog:
    name: Prepare changelog
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Upload Changelog Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ChangelogStuff
          path: ./CHANGELOG.md
          
  build:
    name: Build release
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish
        
      - name: Upload ServerlessUI Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ServerlesUI
          path: D:\a\DatabaseManager\DatabaseManager\DatabaseManager.ServerLessClient\bin\Debug\net6.0\publish\
          
      - name: Upload Hosted Server Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: HostedServer
          path: D:\a\DatabaseManager\DatabaseManager\DatabaseManager\Server\bin\Debug\net6.0\publish\
          
  release:
    name: Release Project
    runs-on: windows-2022
    needs: build
    steps:
      - name: Download changelog
        uses: actions/download-artifact@v2
        with:
            name: ChangelogStuff
      - name: Download site content ServerlesUI
        uses: actions/download-artifact@v2
        with:
          name: ServerlesUI
          path: serverlesui
      - name: View ServerlessUI content
        run: dir serverlesui
      - name: Archive ServerlessUI content
        uses: thedoctor0/zip-release@master
        with:
          path: serverlesui
          filename: ServerlessUI.zip
      - name: Download site content HostedServer
        uses: actions/download-artifact@v2
        with:
          name: HostedServer
          path: hostedserver
      - name: View HostedServer content
        run: dir hostedserver
      - name: Archive HostedServer content
        uses: thedoctor0/zip-release@master
        with:
          path: hostedserver
          filename: HostedServer.zip
